name: global_sports_live
description: Global Sports Live - Score & Match Analysis - API e747e4108a3f5543924daf0ab654f865
publish_to: 'none'
version: 1.0.0+58

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  google_mobile_ads: ^4.0.0
  flutter_local_notifications: ^16.3.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_full.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#0A1931"
    theme_color: "#0A1931"
