                                                                                                          @override
                                                                                                                                                                                                                                                                                                                            Widget build(BuildContext context){
                                                                                                                                                                                                                                                                                                                                return Scaffold(
                                                                                                                                                                                                                                                                                                                                      backgroundColor:const Color(0xFF0A0E1A),
                                                                                                                                                                                                                                                                                                                                            appBar:AppBar(backgroundColor:const Color(0xFF0A0E1A),title:Text('${match['home']} vs ${match['away']}',style:const TextStyle(fontSize:13))),
                                                                                                                                                                                                                                                                                                                                                  body:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(children:[
                                                                                                                                                                                                                                                                                                                                                          Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFF151A2B),borderRadius:BorderRadius.circular(12)),child:Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly,children:[Text(match['home'],style:const TextStyle(color:Colors.white,fontWeight:FontWeight.bold)),Text(match['score'],style:const TextStyle(color:Color(0xFF00C853),fontSize:24,fontWeight:FontWeight.bold)),Text(match['away'],style:const TextStyle(color:Colors.white,fontWeight:FontWeight.bold))])),
                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height:12),
                                                                                                                                                                                                                                                                                                                                                                          Container(height:180,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFF151A2B),borderRadius:BorderRadius.circular(12)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Attack Momentum',style:TextStyle(color:Colors.white,fontWeight:FontWeight.bold)),const SizedBox(height:15),Expanded(child:LineChart(LineChartData(gridData:const FlGridData(show:false),titlesData:const FlTitlesData(show:false),borderData:FlBorderData(show:false),lineBarsData:[LineChartBarData(spots:const[FlSpot(0,1),FlSpot(1,3),FlSpot(2,2),FlSpot(3,4),FlSpot(4,3),FlSpot(5,5)],isCurved:true,color:const Color(0xFF00C853),barWidth:3,dotData:const FlDotData(show:false))])))])),
                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height:12),
                                                                                                                                                                                                                                                                                                                                                                                          Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:const Color(0xFF151A2B),borderRadius:BorderRadius.circular(12)),child:Column(children:[row('xG','1.84','0.72'),row('Possession','62%','38%'),row('Shots','7','3'),row('Corners','8','2')])),
                                                                                                                                                                                                                                                                                                                                                                                                ])),
                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                        Widget row(String l,String h,String a)=>Padding(padding:const EdgeInsets.symmetric(vertical:6),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(h,style:const TextStyle(color:Colors.white)),Text(l,style:const TextStyle(color:Colors.white54,fontSize:11)),Text(a,style:const TextStyle(color:Colors.white))]));
                                                                                                                                                                                                                                                                                                                                                                                                        }
